openapi: 3.0.4
info:
  title: MySuvaUniversity API
  description: API for MySuvaUniversity functionality.
  contact:
    name: Suva
    url: https://github.com/suva-ch/opencontent-api
    email: no-reply@suva.ch
  license:
    name: Apache License 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
  version: v1
servers:
  - url: https://www.suva.ch/contentApi/
    description: Production server
  - url: https://intg.suva.ch/contentApi/
    description: Staging server
paths:
  /MySuvaUniversity/GetLearningUnit:
    get:
      tags:
        - MySuvaUniversity
      summary: Get learning unit
      description: Retrieves a learning unit by its unique item ID and language.
      operationId: GetLearningUnit
      parameters:
        - name: itemId
          in: query
          description: Unique item ID of the learning unit
          required: true
          schema:
            type: string
        - name: language
          in: query
          description: Language code
          schema:
            type: string
            default: de-CH
        - name: api-version
          in: query
          schema:
            type: string
      responses:
        '200':
          description: Returns the learning unit.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LearningUnit'
  /MySuvaUniversity/GetLearningUnits:
    get:
      tags:
        - MySuvaUniversity
      summary: Get all learning units
      description: Retrieves a list of all learning units for the specified language.
      operationId: GetLearningUnits
      parameters:
        - name: language
          in: query
          description: Language code
          schema:
            type: string
            default: de-CH
        - name: api-version
          in: query
          schema:
            type: string
      responses:
        '200':
          description: Returns the list of learning units.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/LearningUnit'
  /MySuvaUniversity/GetAreas:
    get:
      tags:
        - MySuvaUniversity
      summary: Get areas
      description: Retrieves a list of areas for the specified language.
      operationId: GetAreas
      parameters:
        - name: language
          in: query
          description: Language code
          schema:
            type: string
            default: de-CH
        - name: api-version
          in: query
          schema:
            type: string
      responses:
        '200':
          description: Returns the list of areas.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Area'
  /MySuvaUniversity/GetRoles:
    get:
      tags:
        - MySuvaUniversity
      summary: Get roles
      description: Retrieves a list of roles for the specified language.
      operationId: GetRoles
      parameters:
        - name: language
          in: query
          description: Language code
          schema:
            type: string
            default: de-CH
        - name: api-version
          in: query
          schema:
            type: string
      responses:
        '200':
          description: Returns the list of roles.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Role'
  /MySuvaUniversity/GetFaqs:
    get:
      tags:
        - MySuvaUniversity
      summary: Get FAQs
      description: Retrieves a list of FAQs for the specified language.
      operationId: GetFaqs
      parameters:
        - name: language
          in: query
          description: Language code
          schema:
            type: string
            default: de-CH
        - name: api-version
          in: query
          schema:
            type: string
      responses:
        '200':
          description: Returns the list of FAQs.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Faq'
components:
  schemas:
    Area:
      title: Area
      type: object
      allOf:
        - $ref: '#/components/schemas/BaseItem'
      additionalProperties: false
      description: 'Represents an area in MySuvaUniversity, categorizing learning units or content.'
    BaseItem:
      title: BaseItem
      type: object
      properties:
        id:
          type: string
          description: Unique identifier of the item.
          nullable: true
        title:
          type: string
          description: Title of the item.
          nullable: true
      additionalProperties: false
      description: 'Base class for MySuvaUniversity items, containing common properties like identifier and title.'
    ContentElement:
      title: ContentElement
      required:
        - $type
      type: object
      allOf:
        - $ref: '#/components/schemas/BaseItem'
      properties:
        $type:
          type: string
          description: Type of the content element.
          nullable: true
        name:
          type: string
          description: Name of the content element.
          nullable: true
        contentElementType:
          $ref: '#/components/schemas/ContentElementType'
      additionalProperties: false
      description: 'Base class for content elements in MySuvaUniversity, representing various types of learning content.'
      discriminator:
        propertyName: $type
    ContentElementType:
      title: ContentElementType
      type: object
      properties:
        name:
          type: string
          description: Name of the content element type.
          nullable: true
        id:
          type: string
          description: Unique identifier of the content element type.
          nullable: true
      additionalProperties: false
      description: 'Represents the type metadata for a content element in MySuvaUniversity, including its name and identifier.'
    Faq:
      title: Faq
      type: object
      properties:
        id:
          type: string
          description: Unique identifier of the FAQ.
          nullable: true
        name:
          type: string
          description: Name of the FAQ.
          nullable: true
        questions:
          type: array
          items:
            $ref: '#/components/schemas/FaqQuestion'
          description: Collection of questions in the FAQ.
          nullable: true
      additionalProperties: false
      description: 'Represents a frequently asked question (FAQ) set in MySuvaUniversity, containing a collection of questions.'
    FaqQuestion:
      title: FaqQuestion
      type: object
      properties:
        id:
          type: string
          description: Unique identifier of the FAQ question.
          nullable: true
        title:
          type: string
          description: Title of the FAQ question.
          nullable: true
        name:
          type: string
          description: Name of the FAQ question.
          nullable: true
        text:
          type: string
          description: Text content of the FAQ question.
          nullable: true
      additionalProperties: false
      description: Represents a single question within a MySuvaUniversity FAQ set.
    ImageField:
      type: object
      properties:
        alt:
          type: string
          nullable: true
        src:
          type: string
          nullable: true
      additionalProperties: false
    LearningUnit:
      title: LearningUnit
      type: object
      allOf:
        - $ref: '#/components/schemas/BaseItem'
      properties:
        description:
          type: string
          description: Description of the learning unit.
          nullable: true
        area:
          $ref: '#/components/schemas/Area'
        roles:
          type: array
          items:
            $ref: '#/components/schemas/Role'
          description: Roles associated with the learning unit.
          nullable: true
        expectedDurationInMinutes:
          type: integer
          description: Expected duration of the learning unit in minutes.
          format: int32
        learningTargets:
          type: string
          description: Learning targets of the learning unit.
          nullable: true
        image:
          $ref: '#/components/schemas/ImageField'
        lessons:
          type: array
          items:
            $ref: '#/components/schemas/Lesson'
          description: Lessons included in the learning unit.
          nullable: true
      additionalProperties: false
      description: 'Represents a learning unit in MySuvaUniversity, containing lessons and associated metadata.'
    Lesson:
      title: Lesson
      type: object
      allOf:
        - $ref: '#/components/schemas/BaseItem'
      properties:
        name:
          type: string
          description: Name of the lesson.
          nullable: true
        contentElements:
          type: array
          items:
            title: ContentElement
            oneOf:
              - $ref: '#/components/schemas/ModuleText'
              - $ref: '#/components/schemas/Quiz'
              - $ref: '#/components/schemas/Slider'
              - $ref: '#/components/schemas/Video'
            description: 'Base class for content elements in MySuvaUniversity, representing various types of learning content.'
          description: Collection of content elements in the lesson.
          nullable: true
        quizzes:
          type: array
          items:
            $ref: '#/components/schemas/Quiz'
          description: Collection of quizzes in the lesson.
          nullable: true
      additionalProperties: false
      description: 'Represents a lesson in MySuvaUniversity, containing content elements and quizzes.'
    ModuleText:
      title: ModuleText
      type: object
      allOf:
        - $ref: '#/components/schemas/ContentElement'
      properties:
        text:
          type: string
          description: Text content of the module.
          nullable: true
      additionalProperties: false
      description: 'Represents a text-based content element in MySuvaUniversity, used for textual learning content.'
    Quiz:
      title: Quiz
      type: object
      allOf:
        - $ref: '#/components/schemas/ContentElement'
      properties:
        questions:
          type: array
          items:
            $ref: '#/components/schemas/QuizQuestion'
          description: Collection of questions in the quiz.
          nullable: true
      additionalProperties: false
      description: 'Represents a quiz content element in MySuvaUniversity, containing a collection of questions.'
    QuizAnswer:
      title: QuizAnswer
      type: object
      allOf:
        - $ref: '#/components/schemas/BaseItem'
      properties:
        answerText:
          type: string
          description: Text of the answer.
          nullable: true
        isCorrect:
          type: boolean
          description: Indicates whether the answer is correct.
      additionalProperties: false
      description: Represents a single answer within a MySuvaUniversity quiz question.
    QuizQuestion:
      title: QuizQuestion
      type: object
      allOf:
        - $ref: '#/components/schemas/BaseItem'
      properties:
        answers:
          type: array
          items:
            $ref: '#/components/schemas/QuizAnswer'
          description: Collection of answers for the question.
          nullable: true
        questionText:
          type: string
          description: Text of the question.
          nullable: true
      additionalProperties: false
      description: Represents a single question within a MySuvaUniversity quiz.
    Role:
      title: Role
      type: object
      allOf:
        - $ref: '#/components/schemas/BaseItem'
      additionalProperties: false
      description: 'Represents a role associated with learning units in MySuvaUniversity, defining user or participant categories.'
    Slider:
      title: Slider
      type: object
      allOf:
        - $ref: '#/components/schemas/ContentElement'
      properties:
        sliderItems:
          type: array
          items:
            $ref: '#/components/schemas/SliderItem'
          description: Collection of slider items.
          nullable: true
      additionalProperties: false
      description: 'Represents a slider content element in MySuvaUniversity, containing a collection of slider items for visual presentation.'
    SliderItem:
      title: SliderItem
      type: object
      properties:
        imageSrc:
          type: string
          description: Source URL of the image.
          nullable: true
        imageAlt:
          type: string
          description: Alt text for the image.
          nullable: true
        text:
          type: string
          description: Text associated with the slider item.
          nullable: true
      additionalProperties: false
      description: 'Represents a single item within a MySuvaUniversity slider, containing image and text content.'
    Video:
      title: Video
      type: object
      allOf:
        - $ref: '#/components/schemas/ContentElement'
      properties:
        vimeoId:
          type: string
          description: Vimeo ID of the video.
          nullable: true
        transcript:
          type: string
          description: Transcript of the video.
          nullable: true
        coverImageSrc:
          type: string
          description: Source URL of the cover image.
          nullable: true
        coverImageAlt:
          type: string
          description: Alt text for the cover image.
          nullable: true
      additionalProperties: false
      description: 'Represents a video content element in MySuvaUniversity, including video metadata and cover image details.'
  securitySchemes:
    ApiKey:
      type: apiKey
      description: ApiKey must appear in header
      name: ApiKey
      in: header
security:
  - ApiKey: [ ]
tags:
  - name: MySuvaUniversity
    description: 'API for managing and retrieving MySuvaUniversity-related data, including learning units, areas, roles, and FAQs.'